name: ai_interview
description: "AI Interview Coach for Junior Developer."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.3.0
  flex_color_scheme: ^8.1.1
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.9.1
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  kakao_flutter_sdk_user: ^1.9.5
  kakao_flutter_sdk_common: ^1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env


